module.exports = {
  "rules": {
    "at-rule-empty-line-before": ["always", {
      "except": ["blockless-group", "first-nested"],
      "ignore": ["after-comment"]
    }],
    "at-rule-no-vendor-prefix": true,
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always-single-line",
    "block-no-empty": true,
    "block-no-single-line": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": null,
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "color-hex-length": "short",
    "color-named": "never",
    "color-no-hex": null,
    "color-no-invalid-hex": true,
    "comment-empty-line-before": null,
    "comment-whitespace-inside": null,
    "custom-media-pattern": null,
    "custom-property-no-outside-root": null,
    "custom-property-pattern": null,
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-properties-order": [{
      emptyLineBefore: "null",
      properties: [
        "display",
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "float",
        "width",
        "max-width",
        "height",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "appearance",
        "background",
        "background-color",
        "background-image",
        "background-position",
        "background-repeat",
        "background-size",
        "border",
        "border-top",
        "border-right",
        "border-bottom",
        "border-left",
        "border-radius",
        "box-shadow",
        "box-sizing",
        "clear",
        "color",
        "content",
        "cursor",
        "font",
        "font-family",
        "font-feature-settings",
        "font-size",
        "font-style",
        "font-weight",
        "letter-spacing",
        "line-height",
        "list-style",
        "list-style-image",
        "list-style-position",
        "list-style-type",
        "opacity",
        "overflow",
        "text-align",
        "text-decoration",
        "text-transform",
        "transform",
        "transition",
        "user-select",
        "vertical-align",
        "z-index"
      ]
    }],
    "declaration-block-semicolon-newline-after": "always-multi-line",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    "declaration-colon-newline-after": null,
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-no-important": true,
    "font-family-name-quotes": "double-unless-keyword",
    "font-weight-notation": "numeric",
    "function-blacklist": null,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-parentheses-newline-inside": "never-multi-line",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "double",
    "function-whitelist": null,
    "function-whitespace-after": "always",
    "indentation": 2,
    "max-empty-lines": 1,
    "max-line-length": 80,
    "max-nesting-depth": 2,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-no-missing-punctuation": true,
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "media-query-parentheses-space-inside": "never",
    "no-browser-hacks": true,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "no-eol-whitespace": true,
    "no-invalid-double-slash-comments": true,
    "no-missing-eof-newline": true,
    "no-unknown-animations": true,
    "no-unsupported-browser-features": [null, {
      "browsers": "> 1%, last 2 versions, ie >= 10"
    }],
    "number-leading-zero": "always",
    "number-max-precision": [2, 4],
    "number-no-trailing-zeros": true,
    "number-zero-length-no-unit": true,
    "property-blacklist": null,
    "property-no-vendor-prefix": true,
    "property-unit-blacklist": null,
    "property-unit-whitelist": null,
    "property-value-blacklist": null,
    "property-value-whitelist": null,
    "property-whitelist": null,
    "rule-nested-empty-line-before": ["always-multi-line", {
      "except": ["first-nested"]
    }],
    "root-no-standard-properties": true,
    "rule-non-nested-empty-line-before": "always",
    "selector-class-pattern": null,
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-id-pattern": "always",
    "selector-list-comma-newline-after": "always-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "selector-max-specificity": "0,3,1",
    "selector-no-attribute": null,
    "selector-no-combinator": null,
    "selector-no-id": true,
    "selector-no-type": null,
    "selector-no-universal": null,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-element-colon-notation": "single",
    "selector-root-no-composition": true,
    "string-no-newline": true,
    "string-quotes": "double",
    "time-no-imperceptible": true,
    "unit-blacklist": null,
    "unit-whitelist": null,
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "value-no-vendor-prefix": true
  },
}
